export interface SpellLocalization {
    nameIt?: string;
    descriptionIt?: string;
}

const SPELL_LOCALIZATIONS: Record<string, SpellLocalization> = {
    "acid arrow": { nameIt: "Freccia acida" },
    "aid": { nameIt: "Aiuto" },
    "alarm": { nameIt: "Allarme" },
    "animal friendship": { nameIt: "Amicizia con gli animali" },
    "animate dead": { nameIt: "Animare morti" },
    "animated scroll": { nameIt: "Pergamena animata" },
    "antipathy/sympathy": { nameIt: "Antipatia/Simpatia" },
    "arcane eye": { nameIt: "Occhio arcano" },
    "arcane gate": { nameIt: "Portale arcano" },
    "arcane lock": { nameIt: "Blocco arcano" },
    "arcane hand": { nameIt: "Mano arcana" },
    "arcane muscles": { nameIt: "Muscoli arcani" },
    "arms of hadar": { nameIt: "Armi di Hadar" },
    "aura of life": { nameIt: "Aura di vita" },
    "aura of purity": { nameIt: "Aura di purezza" },
    "aura of vitality": { nameIt: "Aura di vitalità" },
    "augury": { nameIt: "Presagio" },
    "bane": { nameIt: "Anatema" },
    "banishment": { nameIt: "Esilio" },
    "banishing smite": { nameIt: "Punizione esiliatrice" },
    "barkskin": { nameIt: "Pelle coriacea" },
    "beacon of hope": { nameIt: "Faro di speranza" },
    "beast bond": { nameIt: "Legame con le bestie" },
    "beast sense": { nameIt: "Percepire con le bestie" },
    "benediction": { nameIt: "Benedizione" },
    "bless": {
        nameIt: "Benedizione",
        descriptionIt: "Fino a tre creature aggiungono 1d4 ai tiri per colpire e ai tiri salvezza per la durata dell'incantesimo.",
    },
    "bless the dead": { nameIt: "Benedizione dei morti" },
    "blight": { nameIt: "Appassire" },
    "blink": { nameIt: "Lampeggiare" },
    "blur": { nameIt: "Sfocatura" },
    "blood tide": { nameIt: "Marea di sangue" },
    "black tentacles": { nameIt: "Tentacoli neri" },
    "black goat's blessing": { nameIt: "Benedizione della Capra Nera" },
    "biting arrow": { nameIt: "Freccia mordente" },
    "blade of disaster": { nameIt: "Lama del disastro" },
    "blade ward": { nameIt: "Interdizione alle lame" },
    "call lightning": { nameIt: "Invocare il fulmine" },
    "booming blade": { nameIt: "Lama tonante" },
    "branding smite": { nameIt: "Punizione marchiante" },
    "burning hands": { nameIt: "Mani brucianti" },
    "calm emotions": { nameIt: "Calmare emozioni" },
    "cause fear": { nameIt: "Incutere paura" },
    "chain lightning": { nameIt: "Cadena di fulmini" },
    "charm person": { nameIt: "Charme su persone" },
    "circle of death": { nameIt: "Cerchio della morte" },
    "circle of power": { nameIt: "Cerchio di potere" },
    "clairvoyance": { nameIt: "Chiaroveggenza" },
    "cone of cold": { nameIt: "Cono di freddo" },
    "conjure barrage": { nameIt: "Sbarramento evanescente" },
    "cloudkill": { nameIt: "Nube mortale" },
    "color spray": { nameIt: "Spruzzo colorato" },
    "command": { nameIt: "Comando" },
    "commune": { nameIt: "Comunione" },
    "commune with nature": { nameIt: "Comunione con la natura" },
    "compelled duel": { nameIt: "Duello forzato" },
    "comprehend languages": { nameIt: "Comprensione dei linguaggi" },
    "compulsion": { nameIt: "Coercizione" },
    "contingency": { nameIt: "Contingenza" },
    "continual flame": { nameIt: "Fiamma perenne" },
    "control water": { nameIt: "Controllare acqua" },
    "counterspell": {
        nameIt: "Controincantesimo",
        descriptionIt: "Interrompi il lancio di un altro incantesimo che vedi entro gittata.",
    },
    "create food and water": { nameIt: "Creare cibo e acqua" },
    "create or destroy water": { nameIt: "Creare o distruggere acqua" },
    "creation": { nameIt: "Creazione" },
    "cure wounds": {
        nameIt: "Cura ferite",
        descriptionIt: "Una creatura toccata recupera punti ferita pari a 1d8 + il tuo modificatore di caratteristica da incantatore.",
    },
    "crusader's mantle": { nameIt: "Manto del crociato" },
    "darkness": { nameIt: "Oscurità" },
    "darkvision": { nameIt: "Scurovisione" },
    "daylight": { nameIt: "Luce diurna" },
    "demiplane": { nameIt: "Semipiano" },
    "death ward": { nameIt: "Interdizione alla morte" },
    "detect evil and good": { nameIt: "Individuazione del bene e del male" },
    "detect magic": {
        nameIt: "Individuazione del magico",
        descriptionIt: "Per la durata percepisci la presenza della magia entro 9 metri e puoi identificarne la scuola se ne vedi l'aura.",
    },
    "detect poison and disease": { nameIt: "Individuazione delle malattie e dei veleni" },
    "detect thoughts": { nameIt: "Individuazione dei pensieri" },
    "dimension door": { nameIt: "Porta dimensionale" },
    "disguise self": { nameIt: "Camuffare se stesso" },
    "distort value": { nameIt: "Alterare valore" },
    "dispel magic": {
        nameIt: "Dissolvi magie",
        descriptionIt: "Scegli un incantesimo, un effetto magico o una magia persistente e prova a terminarla.",
    },
    "dissonant whispers": { nameIt: "Bisbigli dissonanti" },
    "divination": { nameIt: "Divinazione" },
    "divine favor": { nameIt: "Favore divino" },
    "dominate beast": { nameIt: "Dominare bestie" },
    "dominate person": { nameIt: "Dominare persone" },
    "destructive wave": { nameIt: "Ondata devastante" },
    "dream": { nameIt: "Sogno" },
    "dream of the blue veil": { nameIt: "Sogno del velo azzurro" },
    "earth tremor": { nameIt: "Tremito della terra" },
    "elemental weapon": { nameIt: "Arma elementale" },
    "enhance ability": { nameIt: "Caratteristica potenziata" },
    "enlarge/reduce": { nameIt: "Ingrandire/Ridurre" },
    "ensnaring strike": { nameIt: "Colpo intrappolante" },
    "entangle": { nameIt: "Intrappolare" },
    "enthrall": { nameIt: "Estasiare" },
    "fabricate": { nameIt: "Fabbricare" },
    "faerie fire": { nameIt: "Fuoco fatato" },
    "false life": { nameIt: "Vita falsa" },
    "feather fall": { nameIt: "Caduta morbida" },
    "find familiar": { nameIt: "Trova famiglio" },
    "finger of death": { nameIt: "Dito della morte" },
    "fire shield": {
        nameIt: "Scudo di fuoco",
        descriptionIt: "Fiamme o gelo ti avvolgono e puniscono chi ti colpisce in mischia.",
    },
    "fireball": { nameIt: "Palla di fuoco" },
    "fire storm": { nameIt: "Tempesta di fuoco" },
    "flame blade": { nameIt: "Lama di fiamma" },
    "flame strike": { nameIt: "Colpo infuocato" },
    "flaming sphere": { nameIt: "Sfera infuocata" },
    "flesh to stone": { nameIt: "Pietrificare" },
    "fly": { nameIt: "Volare" },
    "fog cloud": { nameIt: "Nube di nebbia" },
    "forcecage": { nameIt: "Gabbia di forza" },
    "freedom of movement": { nameIt: "Libertà di movimento" },
    "freezing sphere": { nameIt: "Sfera congelante" },
    "grasping vine": { nameIt: "Vite afferrante" },
    "gaseous form": { nameIt: "Forma gassosa" },
    "gate": { nameIt: "Portale" },
    "gentle repose": { nameIt: "Riposo gentile" },
    "gift of alacrity": { nameIt: "Dono dell'alacrità" },
    "globe of invulnerability": { nameIt: "Globo di invulnerabilità" },
    "glyph of warding": { nameIt: "Glifo di interdizione" },
    "grease": { nameIt: "Grasso" },
    "greater invisibility": {
        nameIt: "Invisibilità superiore",
        descriptionIt: "Il bersaglio resta invisibile anche mentre attacca o lancia incantesimi.",
    },
    "greater restoration": { nameIt: "Ristorare superiore" },
    "guardian of faith": { nameIt: "Guardiano della fede" },
    "green-flame blade": { nameIt: "Lama di fiamma verde" },
    "guidance": { nameIt: "Guida" },
    "guiding bolt": { nameIt: "Dardo Tracciante" },
    "gust of wind": { nameIt: "Folata di vento" },
    "hallucinatory terrain": { nameIt: "Terreno illusorio" },
    "haste": { nameIt: "Velocità" },
    "heal": { nameIt: "Guarigione" },
    "healing word": {
        nameIt: "Parola guaritrice",
        descriptionIt: "Una creatura a gittata recupera 1d4 + il tuo modificatore di caratteristica da incantatore come azione bonus.",
    },
    "heroes' feast": { nameIt: "Banchetto degli eroi" },
    "heroism": { nameIt: "Eroismo" },
    "hex": { nameIt: "Maleficio" },
    "hideous laughter": { nameIt: "Risata incontenibile" },
    "hold monster": { nameIt: "Blocca mostri" },
    "hold person": { nameIt: "Blocca persone" },
    "hunger of hadar": { nameIt: "Fame di Hadar" },
    "hunter's mark": { nameIt: "Marchio del cacciatore" },
    "hypnotic pattern": { nameIt: "Trama ipnotica" },
    "ice storm": { nameIt: "Tempesta di ghiaccio" },
    "id insinuation": { nameIt: "Insinuazione mentale" },
    "identify": { nameIt: "Identificare" },
    "illusory script": { nameIt: "Scritto illusorio" },
    "incendiary cloud": { nameIt: "Nube incendiaria" },
    "inflict wounds": { nameIt: "Infliggi ferite" },
    "insect plague": { nameIt: "Piaga degli insetti" },
    "intellect fortress": { nameIt: "Fortezza dell'intelletto" },
    "irresistible dance": { nameIt: "Danza irresistibile" },
    "invisibility": {
        nameIt: "Invisibilità",
        descriptionIt: "Una creatura toccata diventa invisibile finché l'incantesimo dura o finché non attacca o lancia un altro incantesimo.",
    },
    "lesser restoration": { nameIt: "Ristorare inferiore" },
    "leomund's tiny hut": { nameIt: "Capanna di Leomund" },
    "light": { nameIt: "Luce" },
    "lightning bolt": { nameIt: "Fulmine" },
    "lightning lure": { nameIt: "Richiamo fulmineo" },
    "locate creature": { nameIt: "Localizza creatura" },
    "locate object": { nameIt: "Localizza oggetto" },
    "mage hand": { nameIt: "Mano magica" },
    "magic circle": { nameIt: "Cerchio magico" },
    "magic missile": { nameIt: "Dardo incantato" },
    "magic weapon": { nameIt: "Arma magica" },
    "major image": { nameIt: "Immagine maggiore" },
    "mass cure wounds": { nameIt: "Cura ferite di massa" },
    "mass healing word": { nameIt: "Parola guaritrice di massa" },
    "meld into stone": { nameIt: "Fondersi nella pietra" },
    "mending": { nameIt: "Riparare" },
    "message": { nameIt: "Messaggio" },
    "mind sliver": { nameIt: "Scheggia mentale" },
    "mirror image": { nameIt: "Immagine speculare" },
    "mislead": { nameIt: "Fuorviare" },
    "minor illusion": { nameIt: "Illusione minore" },
    "misty step": { nameIt: "Passo velato" },
    "modify memory": { nameIt: "Modificare memoria" },
    "moonbeam": { nameIt: "Raggio lunare" },
    "mordenkainen's private sanctum": { nameIt: "Santuario privato di Mordenkainen" },
    "move earth": { nameIt: "Spostare terre" },
    "nondetection": { nameIt: "Anti-individuazione" },
    "nystul's magic aura": { nameIt: "Aura magica di Nystul" },
    "pass without trace": { nameIt: "Passare senza lasciare tracce" },
    "passwall": { nameIt: "Passaparete" },
    "phantasmal force": { nameIt: "Forza fantasma" },
    "phantasmal killer": { nameIt: "Assassino fantasma" },
    "plane shift": { nameIt: "Piano di passaggio" },
    "planar binding": { nameIt: "Vincolo planare" },
    "plant growth": { nameIt: "Crescita vegetale" },
    "polymorph": { nameIt: "Metamorfosi" },
    "power word heal": { nameIt: "Parola del potere guarire" },
    "prayer of healing": { nameIt: "Preghiera di guarigione" },
    "prismatic spray": { nameIt: "Spruzzo prismatico" },
    "prismatic wall": { nameIt: "Muro prismatico" },
    "protection from energy": { nameIt: "Protezione dall'energia" },
    "protection from evil and good": { nameIt: "Protezione dal bene e dal male" },
    "ray of enfeeblement": { nameIt: "Raggio di affaticamento" },
    "ray of sickness": { nameIt: "Raggio di malattia" },
    "raise dead": { nameIt: "Rianimare morti" },
    "rary's telepathic bond": { nameIt: "Legame telepatico di Rary" },
    "resilient sphere": { nameIt: "Sfera resiliente" },
    "revivify": { nameIt: "Rivivificare" },
    "sanctuary": { nameIt: "Santuario" },
    "scorching ray": { nameIt: "Raggio rovente" },
    "scrying": { nameIt: "Scrutare" },
    "searing smite": { nameIt: "Punizione ardente" },
    "see invisibility": { nameIt: "Vedere invisibilità" },
    "sending": { nameIt: "Inviare" },
    "seeming": { nameIt: "Sembrare" },
    "sleet storm": { nameIt: "Tempesta di nevischio" },
    "shadow blade": { nameIt: "Lama ombra" },
    "shatter": { nameIt: "Frantumare" },
    "shield": {
        nameIt: "Scudo",
        descriptionIt: "Una barriera invisibile di forza magica ti concede +5 alla CA fino all'inizio del tuo turno successivo.",
    },
    "shield of faith": {
        nameIt: "Scudo della fede",
        descriptionIt: "Un campo scintillante conferisce a una creatura scelta +2 alla CA per la durata dell'incantesimo.",
    },
    "silent image": { nameIt: "Immagine silenziosa" },
    "silence": { nameIt: "Silenzio" },
    "sleep": {
        nameIt: "Sonno",
        descriptionIt: "Le creature nell'area cadono addormentate e non possono essere svegliate finché l'effetto dura.",
    },
    "slow": { nameIt: "Lentezza" },
    "speak with animals": { nameIt: "Parlare con gli animali" },
    "speak with dead": { nameIt: "Parlare con i morti" },
    "speak with plants": { nameIt: "Parlare con i vegetali" },
    "spike growth": { nameIt: "Crescita di spine" },
    "spirit guardians": { nameIt: "Guardiani spirituali" },
    "spirit shroud": { nameIt: "Sudario spirituale" },
    "spiritual weapon": { nameIt: "Arma spirituale" },
    "summon aberration": { nameIt: "Evoca aberrazione" },
    "summon beast": { nameIt: "Evoca bestia" },
    "summon celestial": { nameIt: "Evoca celestiale" },
    "summon construct": { nameIt: "Evoca costrutto" },
    "summon elemental": { nameIt: "Evoca elementale" },
    "summon fey": { nameIt: "Evoca fatato" },
    "summon fiend": { nameIt: "Evoca immondo" },
    "summon shadowspawn": { nameIt: "Evoca creatura ombra" },
    "summon undead": { nameIt: "Evoca non morto" },
    "stone shape": { nameIt: "Scolpire pietra" },
    "stoneskin": { nameIt: "Pelle di pietra" },
    "sunbeam": { nameIt: "Raggio solare" },
    "sunburst": { nameIt: "Esplosione solare" },
    "suggestion": { nameIt: "Suggestione" },
    "symbol": { nameIt: "Simbolo" },
    "sword burst": { nameIt: "Esplosione di spade" },
    "tasha's caustic brew": { nameIt: "Bollitura caustica di Tasha" },
    "tasha's mind whip": { nameIt: "Frusta mentale di Tasha" },
    "tenser's floating disk": { nameIt: "Disco fluttuante di Tenser" },
    "telekinesis": { nameIt: "Telecinesi" },
    "telepathic bond": { nameIt: "Legame telepatico" },
    "teleportation circle": { nameIt: "Cerchio di teletrasporto" },
    "thaumaturgy": { nameIt: "Taumaturgia" },
    "thunderwave": {
        nameIt: "Onda tonante",
        descriptionIt: "Una scossa di forza tonante parte da te e spinge via le creature nell'area infliggendo danni da tuono.",
    },
    "tongues": { nameIt: "Linguaggi" },
    "true seeing": { nameIt: "Visione del vero" },
    "tree stride": { nameIt: "Passo degli alberi" },
    "vampiric touch": { nameIt: "Tocco vampirico" },
    "wall of fire": { nameIt: "Muro di fuoco" },
    "wall of force": { nameIt: "Muro di forza" },
    "wall of stone": { nameIt: "Muro di pietra" },
    "warding bond": { nameIt: "Vincolo protettivo" },
    "web": { nameIt: "Ragnatela" },
    "weird": { nameIt: "Orrore" },
    "wind wall": { nameIt: "Muro di vento" },
    "wish": { nameIt: "Desiderio" },
    "word of recall": { nameIt: "Parola di richiamo" },
    "zone of truth": { nameIt: "Zona di verità" },
};

function normalizeSpellName(name: string) {
    return name.trim().replace(/[’']/g, "'").replace(/\s+/g, " ").toLowerCase();
}

export function getSpellLocalization(name: string | null | undefined) {
    if (!name) return undefined;
    return SPELL_LOCALIZATIONS[normalizeSpellName(name)];
}

export function formatSpellDisplayName(name: string | null | undefined) {
    if (!name) return "";
    const localized = getSpellLocalization(name);
    return localized?.nameIt ? `${name} (${localized.nameIt})` : name;
}
