export const GENERATED_SPELL_LOCALIZATIONS: Record<string, { nameIt?: string; descriptionIt?: string }> = {
  "abhorrent apparition": { nameIt: "Apparizione Abominevole" },
  "abi-dalzim’s horrid wilting": { nameIt: "Inaridimento Orribile di Abi-Dalzim" },
  "abrupt hug": { nameIt: "Abbraccio Improvviso" },
  "absolute command": { nameIt: "Comando Assoluto" },
  "absorb elements": { nameIt: "Assorbire Elementi" },
  "accelerando": { nameIt: "Accelerando" },
  "accelerate": { nameIt: "Accelerare" },
  "acid gate": { nameIt: "Portale d'Acido" },
  "acid rain": { nameIt: "Pioggia Acida" },
  "acid splash": { nameIt: "fiotto acido" },
  "adjust position": { nameIt: "Aggiustare Posizione" },
  "afflict line": { nameIt: "Affliggere la Linea" },
  "aganazzar’s scorcher": { nameIt: "Vampata di Aganazzar" },
  "agonizing mark": { nameIt: "Marchio Agonizzante" },
  "air bubble": { nameIt: "Bolla d'Aria" },
  "air wave": { nameIt: "Onda d'Aria" },
  "alchemical form": { nameIt: "Forma Alchemica" },
  "ale-dritch blast": { nameIt: "Deflagrazione Luppolata" },
  "ally aegis": { nameIt: "Egida dell'Alleato" },
  "alone": { nameIt: "Solitudine" },
  "alter arrow’s fortune": { nameIt: "Alterare la Sorte della Freccia" },
  "alter self": { nameIt: "alterare sé stesso" },
  "altered strike": { nameIt: "Colpo Alterato" },
  "althea’s travel tent": { nameIt: "Tenda da Viaggio di Althea" },
  "ambush": { nameIt: "Imboscata" },
  "ambush chute": { nameIt: "Condotto d'Imboscata" },
  "amplify gravity": { nameIt: "Amplificare la Gravità" },
  "amplify ley field": { nameIt: "Amplificare il Campo Ley" },
  "analyze device": { nameIt: "Analizzare Congegno" },
  "ancestor’s strength": { nameIt: "Forza dell'Antenato" },
  "anchoring rope": { nameIt: "Corda di Ancoraggio" },
  "ancient shade": { nameIt: "Ombra Antica" },
  "angel paradox": { nameIt: "Paradosso dell'Angelo" },
  "angelic guardian": { nameIt: "Guardiano Angelico" },
  "animal messenger": { nameIt: "animale messaggero" },
  "animal shapes": { nameIt: "forme animali" },
  "animate construct": { nameIt: "Animare Costrutto" },
  "animate ghoul": { nameIt: "Animare Ghoul" },
  "animate greater undead": { nameIt: "Animare Non Morti Superiori" },
  "animate objects": { nameIt: "animare oggetti" },
  "anomalous object": { nameIt: "Oggetto Anomalo" },
  "anticipate arcana": { nameIt: "Anticipare Arcani" },
  "anticipate attack": { nameIt: "Anticipare l'Attacco" },
  "anticipate weakness": { nameIt: "Anticipare la Debolezza" },
  "antilife shell": { nameIt: "guscio anti-vita" },
  "antimagic field": { nameIt: "campo anti-magia" },
  "arcane riposte": { nameIt: "Contrattacco Arcano" },
  "arcane sight": { nameIt: "Vista Arcana" },
  "arcane sword": { nameIt: "Spada Arcana" },
  "arcane weapon": { nameIt: "Arma Arcana" },
  "arcanist's magic aura": { nameIt: "Aura Magica dell'Arcanista" },
  "armor of agathys": { nameIt: "armatura di Agathys" },
  "armored formation": { nameIt: "Formazione Corazzata" },
  "armored heart": { nameIt: "Cuore Corazzato" },
  "armored shell": { nameIt: "Guscio Corazzato" },
  "as you were": { nameIt: "Come Prima" },
  "ashardalon’s stride": { nameIt: "Passo di Ashardalon" },
  "ashen memories": { nameIt: "Ricordi Cinerei" },
  "aspect of the dragon": { nameIt: "Aspetto del Drago" },
  "aspect of the moon": { nameIt: "Aspetto della Luna" },
  "aspect of the serpent": { nameIt: "Aspetto del Serpente" },
  "astral projection": { nameIt: "proiezione astrale" },
  "aura of desecration": { nameIt: "Aura di Profanazione" },
  "aura of loathing": { nameIt: "Aura di Aborrimento" },
  "aura of protection or destruction": { nameIt: "Aura di Protezione o Distruzione" },
  "auspicious warning": { nameIt: "Monito Auspicioso" },
  "avert evil eye": { nameIt: "Stornare il Malocchio" },
  "avoid grievous injury": { nameIt: "Scongiurare Gravi Lesioni" },
  "avronin’s astral assembly": { nameIt: "Adunanza Astrale di Avronin" },
  "awaken": { nameIt: "risveglio" },
  "awaken object": { nameIt: "Risvegliare Oggetto" },
  "babble": { nameIt: "Farfugliare" },
  "bad timing": { nameIt: "Tempismo Sfortunato" },
  "banshee wail": { nameIt: "Lamento della Banshee" },
  "bardo": { nameIt: "Bardo" },
  "batsense": { nameIt: "Senso del Pipistrello" },
  "battle chant": { nameIt: "Canto di Battaglia" },
  "battle mind": { nameIt: "Mente Combattiva" },
  "battlecry ballad": { nameIt: "Ballata del Grido di Battaglia" },
  "beast within": { nameIt: "Bestia Interiore" },
  "become nightwing": { nameIt: "Diventare Ala della Notte" },
  "beguiling bet": { nameIt: "Scommessa Ammaliatrice" },
  "beguiling gift": { nameIt: "Dono Ammaliatore" },
  "bestial fury": { nameIt: "Furia Bestiale" },
  "bestow curse": { nameIt: "scagliare maledizione" },
  "betraying bauble": { nameIt: "Gingillo Traditore" },
  "bigby's hand": { nameIt: "mano di bigby" },
  "binding oath": { nameIt: "Giuramento Vincolante" },
  "bitter chains": { nameIt: "Catene Amare" },
  "black goat’s blessing": { nameIt: "Benedizione del Capro Nero" },
  "black hand": { nameIt: "Mano Nera" },
  "black ribbons": { nameIt: "Nastri Neri" },
  "black sunshine": { nameIt: "Luce Solare Nera" },
  "black swan storm": { nameIt: "Tempesta del Cigno Nero" },
  "black well": { nameIt: "Pozzo Nero" },
  "blade barrier": { nameIt: "barriera di lame" },
  "blade of my brother": { nameIt: "Lama di mio Fratello" },
  "blade of wrath": { nameIt: "Lama dell'Ira" },
  "blazing chariot": { nameIt: "Carro Fiammeggiante" },
  "bleating call": { nameIt: "Richiamo Belante" },
  "bleed": { nameIt: "Sanguinare" },
  "blessed halo": { nameIt: "Aureola Benedetta" },
  "blinding smite": { nameIt: "punizione accecante" },
  "blindness/deafness": { nameIt: "cecità/sordità" },
  "blizzard": { nameIt: "Tormenta" },
  "blood and steel": { nameIt: "Sangue e Acciaio" },
  "blood armor": { nameIt: "Armatura di Sangue" },
  "blood lure": { nameIt: "Richiamo di Sangue" },
  "blood offering": { nameIt: "Offerta di Sangue" },
  "blood puppet": { nameIt: "Marionetta di Sangue" },
  "blood scarab": { nameIt: "Scarabeo di Sangue" },
  "blood spoor": { nameIt: "Traccia di Sangue" },
  "blood strike": { nameIt: "Colpo di Sangue" },
  "blood to acid": { nameIt: "Sangue in Acido" },
  "blood-writ bargain": { nameIt: "Patto Scritto col Sangue" },
  "bloodhound": { nameIt: "Segugio" },
  "bloodlust": { nameIt: "Sete di Sangue" },
  "bloodshot": { nameIt: "Colpo di Sangue" },
  "bloody hands": { nameIt: "Mani Sanguinanti" },
  "bloody smite": { nameIt: "Punizione Sanguinosa" },
  "bloom": { nameIt: "Fioritura" },
  "blunted edge": { nameIt: "Filo Smussato" },
  "boiling blood": { nameIt: "Sangue Bollente" },
  "boiling oil": { nameIt: "Olio Bollente" },
  "bolster fortifications": { nameIt: "Rinforzare Fortificazioni" },
  "bolster undead": { nameIt: "Rinvigorire Non Morti" },
  "bombardment of stings": { nameIt: "Bombardamento di Pungiglioni" },
  "bones of the earth": { nameIt: "Ossa della Terra" },
  "booster shot": { nameIt: "Iniezione di Rinforzo" },
  "boreas’s breath": { nameIt: "Soffio di Borea" },
  "borrowed knowledge": { nameIt: "Conoscenza in Prestito" },
  "borrowing": { nameIt: "Prendere in Prestito" },
  "bottled arcana": { nameIt: "Arcano Imbottigliato" },
  "bottomless stomach": { nameIt: "Stomaco Senza Fondo" },
  "bound haze": { nameIt: "Foschia Vincolata" },
  "breathtaking wind": { nameIt: "Vento Mozzafiato" },
  "breeze compass": { nameIt: "Bussola della Brezza" },
  "brimstone infusion": { nameIt: "Infusione di Zolfo" },
  "brittling": { nameIt: "Infragilimento" },
  "broken charge": { nameIt: "Carica Spezzata" },
  "burning halo": { nameIt: "Aureola Bruciante" },
  "burst stone": { nameIt: "Pietra Dirompente" },
  "butterfly effect": { nameIt: "Effetto Farfalla" },
  "by the light of the moon": { nameIt: "Alla Luce della Luna" },
  "by the light of the watchful moon": { nameIt: "Alla Luce della Luna Vigilante" },
  "calculate": { nameIt: "Calcolo" },
  "calculated retribution": { nameIt: "Ritorsione Calcolata" },
  "call shadow mastiff": { nameIt: "Evoca Mastino d'Ombra" },
  "call the hunter": { nameIt: "Richiamo del Cacciatore" },
  "calm beasts": { nameIt: "Calmare Bestie" },
  "calm of the storm": { nameIt: "Calma della Tempesta" },
  "candle’s insight": { nameIt: "Intuizione della Candela" },
  "card throw": { nameIt: "Lancio delle Carte" },
  "carmello-volta’s irksome preserves": { nameIt: "Conserve Fastidiose di Carmello-Volta" },
  "catapult": { nameIt: "Catapulta" },
  "catch the breath": { nameIt: "Riprendere Fiato" },
  "catnap": { nameIt: "Sonnellino" },
  "caustic blood": { nameIt: "Sangue Caustico" },
  "caustic torrent": { nameIt: "Torrente Caustico" },
  "caustic touch": { nameIt: "Tocco Caustico" },
  "celebration": { nameIt: "Celebrazione" },
  "ceremony": { nameIt: "Cerimonia" },
  "chains of the goddess": { nameIt: "Catene della Dea" },
  "chains of torment": { nameIt: "Catene del Tormento" },
  "champion’s weapon": { nameIt: "Arma del Campione" },
  "chaos bolt": { nameIt: "Dardo del Caos" },
  "chaotic form": { nameIt: "Forma Caotica" },
  "chaotic vitality": { nameIt: "Vitalità Caotica" },
  "chaotic world": { nameIt: "Mondo Caotico" },
  "charm monster": { nameIt: "Charma Mostri" },
  "charming aesthetics": { nameIt: "Estetica Affascinante" },
  "child of light and darkness": { nameIt: "Figlio della Luce e dell'Oscurità" },
  "chill touch": { nameIt: "tocco gelido" },
  "chilling words": { nameIt: "Parole Gelide" },
  "chromatic orb": { nameIt: "globo cromatico" },
  "chromatic wave": { nameIt: "Onda Cromatica" },
  "chronal lance": { nameIt: "Lancia Cronale" },
  "circle of devestation": { nameIt: "Cerchio di Devastazione" },
  "circle of wind": { nameIt: "Cerchio del Vento" },
  "circular breathing": { nameIt: "Respirazione Circolare" },
  "clash of glaciers": { nameIt: "Scontro di Ghiacciai" },
  "claws of darkness": { nameIt: "Artigli dell'Oscurità" },
  "claws of the earth dragon": { nameIt: "Artigli del Drago della Terra" },
  "clear the board": { nameIt: "Sgombrare la Scacchiera" },
  "clearing the field": { nameIt: "Sgombrare il Campo" },
  "cloak of shadow": { nameIt: "Mantello d'Ombra" },
  "clockwork bolt": { nameIt: "Dardo a Orologeria" },
  "clone": { nameIt: "clone" },
  "closing in": { nameIt: "Morsa in Chiusura" },
  "cloud of daggers": { nameIt: "nube di pugnali" },
  "cloying darkness": { nameIt: "Oscurità Opprimente" },
  "cobra fangs": { nameIt: "Zanne del Cobra" },
  "cobra's spit": { nameIt: "Sputo del Cobra" },
  "commander's pavilion": { nameIt: "Padiglione del Comandante" },
  "compelled movement": { nameIt: "Movimento Forzato" },
  "compelling fate": { nameIt: "Destino Impellente" },
  "comprehend wild shape": { nameIt: "Comprendere la Forma Selvatica" },
  "confound senses": { nameIt: "Confondere i Sensi" },
  "confusion": { nameIt: "confusione" },
  "conjure animals": { nameIt: "evoca animali" },
  "conjure celestial": { nameIt: "evoca celestiale" },
  "conjure construct": { nameIt: "Evoca Costrutto" },
  "conjure elemental": { nameIt: "evoca elementale" },
  "conjure fey": { nameIt: "evoca folletto" },
  "conjure fey hound": { nameIt: "Evoca Segugio Fatato" },
  "conjure forest defender": { nameIt: "Evoca Difensore della Foresta" },
  "conjure greater spectral dead": { nameIt: "Evoca Morti Spettrali Superiori" },
  "conjure manabane swarm": { nameIt: "Evoca Sciame Flagello del Mana" },
  "conjure minor elementals": { nameIt: "evoca elementali minori" },
  "conjure minor voidborn": { nameIt: "Evoca Nato dal Vuoto Inferiore" },
  "conjure scarab swarm": { nameIt: "Evoca Sciame di Scarabei" },
  "conjure shadow titan": { nameIt: "Evoca Titano delle Ombre" },
  "conjure spectral allies": { nameIt: "Evoca Alleati Spettrali" },
  "conjure spectral dead": { nameIt: "Evoca Morti Spettrali" },
  "conjure undead": { nameIt: "Evoca Non Morti" },
  "conjure voidborn": { nameIt: "Evoca Nato dal Vuoto" },
  "conjure volley": { nameIt: "evoca pioggia di armi" },
  "conjure woodland beings": { nameIt: "evoca creature boschive" },
  "consult the storm": { nameIt: "Consultare la Tempesta" },
  "contact other plane": { nameIt: "contattare altri piani" },
  "contagion": { nameIt: "contagio" },
  "control flames": { nameIt: "Controllo delle Fiamme" },
  "control weather": { nameIt: "controllare tempo atmosferico" },
  "control winds": { nameIt: "Controllo dei Venti" },
  "converse with dragon": { nameIt: "Conversare con i Draghi" },
  "convey inner peace": { nameIt: "Trasmettere Pace Interiore" },
  "cordon of arrows": { nameIt: "cordone di frecce" },
  "corpse explosion": { nameIt: "Esplosione di Cadaveri" },
  "cosmic alignment": { nameIt: "Allineamento Cosmico" },
  "costly victory": { nameIt: "Vittoria a Caro Prezzo" },
  "create bonfire": { nameIt: "Creare Falò" },
  "create homunculus": { nameIt: "Creare Homunculus" },
  "create magen": { nameIt: "Creare Magen" },
  "create ring servant": { nameIt: "Creare Servitore dell'Anello" },
  "create spelljamming helm": { nameIt: "Creare Timone Spelljamming" },
  "create thunderstaff": { nameIt: "Creare Bastone del Tuono" },
  "create undead": { nameIt: "creare non morti" },
  "creeping ice": { nameIt: "Ghiaccio Strisciante" },
  "crown of madness": { nameIt: "corona di follia" },
  "crown of stars": { nameIt: "Corona di Stelle" },
  "crown of thorns": { nameIt: "Corona di Spine" },
  "cruor of visions": { nameIt: "Cruore delle Visioni" },
  "crushing curse": { nameIt: "Maledizione Schiacciante" },
  "crushing haymaker": { nameIt: "Gancio Schiacciante" },
  "crushing trample": { nameIt: "Travolgimento Schiacciante" },
  "cryobomb": { nameIt: "Criobomba" },
  "cryostasis": { nameIt: "Criostasi" },
  "cure beast": { nameIt: "Cura Bestia" },
  "curse of boreas": { nameIt: "Maledizione di Borea" },
  "curse of dust": { nameIt: "Maledizione della Polvere" },
  "curse of formlessness": { nameIt: "Maledizione dell'Informe" },
  "curse of incompetence": { nameIt: "Maledizione dell'Incompetenza" },
  "curse of the grave": { nameIt: "Maledizione della Tomba" },
  "curse of yig": { nameIt: "Maledizione di Yig" },
  "curse ring": { nameIt: "Anello della Maledizione" },
  "cursed gift": { nameIt: "Dono Maledetto" },
  "cynophobia": { nameIt: "Cinofobia" },
  "daggerhawk": { nameIt: "Falco Pugnale" },
  "damaging intel": { nameIt: "Informazioni Dannose" },
  "dancing lights": { nameIt: "luci danzanti" },
  "danse macabre": { nameIt: "Danza Macabra" },
  "dark dementing": { nameIt: "Demenza Oscura" },
  "dark heraldry": { nameIt: "Araldica Oscura" },
  "dark maw": { nameIt: "Fauce Oscura" },
  "dark path": { nameIt: "Sentiero Oscuro" },
  "dark star": { nameIt: "Stella Oscura" },
  "darkbolt": { nameIt: "Dardo Oscuro" },
  "darklight": { nameIt: "Luce Oscura" },
  "dawn": { nameIt: "Alba" },
  "dead walking": { nameIt: "Morto Ambulante" },
  "deadly salvo": { nameIt: "Salva Letale" },
  "deadly sting": { nameIt: "Pungiglione Letale" },
  "deadweight": { nameIt: "Peso Morto" },
  "death god’s touch": { nameIt: "Tocco del Dio della Morte" },
  "decay": { nameIt: "Decomposizione" },
  "decelerate": { nameIt: "Decelerazione" },
  "deep breath": { nameIt: "Respiro Profondo" },
  "defile healing": { nameIt: "Contaminare Guarigione" },
  "delay passing": { nameIt: "Ritardare il Trapasso" },
  "delay potion": { nameIt: "Ritardare Pozione" },
  "delayed blast fireball": { nameIt: "palla di fuoco ritardata" },
  "delayed healing": { nameIt: "Guarigione Ritardata" },
  "demon within": { nameIt: "Demone Interiore" },
  "desiccating breath": { nameIt: "Soffio Disseccante" },
  "desolation": { nameIt: "Desolazione" },
  "destructive resonance": { nameIt: "Risonanza Distruttiva" },
  "detect dragons": { nameIt: "Individuazione dei Draghi" },
  "deva’s wings": { nameIt: "Ali del Deva" },
  "devouring darkness": { nameIt: "Oscurità Divoratrice" },
  "dimensional shove": { nameIt: "Spinta Dimensionale" },
  "disintegrate": { nameIt: "disintegrazione" },
  "dispel evil and good": { nameIt: "dissolvi il bene e il male" },
  "disquieting gaze": { nameIt: "Sguardo Inquietante" },
  "disruptive aura": { nameIt: "Aura Dirompente" },
  "distracting divination": { nameIt: "Divinazione Distraente" },
  "distraction cascade": { nameIt: "Cascata di Distrazione" },
  "divine retribution": { nameIt: "Punizione Divina" },
  "divine word": { nameIt: "parola divina" },
  "dominate monster": { nameIt: "dominare mostri" },
  "doom of ancient decrepitude": { nameIt: "Condanna dell'Antica Decrepitezza" },
  "doom of blue crystal": { nameIt: "Condanna del Cristallo Blu" },
  "doom of consuming fire": { nameIt: "Condanna del Fuoco Divoratore" },
  "doom of dancing blades": { nameIt: "Condanna delle Spade Danzanti" },
  "doom of disenchantment": { nameIt: "Condanna del Disincantamento" },
  "doom of serpent coils": { nameIt: "Condanna delle Spire del Serpente" },
  "doom of the cracked shield": { nameIt: "Condanna dello Scudo Crepato" },
  "doom of the earthen maw": { nameIt: "Condanna delle Fauci Terrene" },
  "doom of the slippery rogue": { nameIt: "Condanna del Ladro Sfuggente" },
  "doom of voracity": { nameIt: "Condanna della Voracità" },
  "door of the far traveler": { nameIt: "Porta del Viaggiatore Lontano" },
  "douse light": { nameIt: "Spegnere la Luce" },
  "draconic smite": { nameIt: "Punizione Draconica" },
  "draconic transformation": { nameIt: "Trasformazione Draconica" },
  "dragon breath": { nameIt: "Soffio di Drago" },
  "dragon roar": { nameIt: "Rugito del Drago" },
  "dragon's breath": { nameIt: "Soffio del Drago" },
  "dragon’s breath": { nameIt: "Soffio del Drago" },
  "dramatic sting": { nameIt: "Puntura Drammatica" },
  "drawmij's instant summons": { nameIt: "evocazioni istantanee di Drawmij" },
  "dreamwine": { nameIt: "Vino dei Sogni" },
  "drown": { nameIt: "Annegare" },
  "druid grove": { nameIt: "Boschetto del Druido" },
  "druidcraft": { nameIt: "artificio druidico" },
  "dryad’s kiss": { nameIt: "Bacio della Driade" },
  "dust devil": { nameIt: "Diavolo di Polvere" },
  "earth barrier": { nameIt: "Barriera di Terra" },
  "earthbind": { nameIt: "Vincolo Terrestre" },
  "earthquake": { nameIt: "terremoto" },
  "earthskimmer": { nameIt: "Sfioraterra" },
  "earworm melody": { nameIt: "Melodia Assillante" },
  "echoes of steel": { nameIt: "Echi d'Acciaio" },
  "ectoplasm": { nameIt: "Ectoplasma" },
  "ego whip": { nameIt: "Frusta dell'Ego" },
  "eidetic memory": { nameIt: "Memoria Eidetica" },
  "eldritch blast": { nameIt: "deflagrazione occulta" },
  "eldritch communion": { nameIt: "Comunione Arcana" },
  "eldritch cube": { nameIt: "Cubo Arcano" },
  "elemental bane": { nameIt: "Flagello Elementale" },
  "elemental horns": { nameIt: "Corna Elementali" },
  "elemental twist": { nameIt: "Torsione Elementale" },
  "emanation of yoth": { nameIt: "Emanazione di Yoth" },
  "emerald eyes": { nameIt: "Occhi di Smeraldo" },
  "enchant ring": { nameIt: "Incantare Anello" },
  "enchanted bloom": { nameIt: "Fioritura Incantata" },
  "encode thoughts": { nameIt: "Codificare Pensieri" },
  "encroaching shadows": { nameIt: "Ombre Incombenti" },
  "encrypt / decrypt": { nameIt: "Cifrare / Decifrare" },
  "endow attribute": { nameIt: "Conferire Attributo" },
  "enemies abound": { nameIt: "Nemici Abbondanti" },
  "energy absorption": { nameIt: "Assorbimento dell'Energia" },
  "energy foreknowledge": { nameIt: "Prescienza dell'Energia" },
  "enervation": { nameIt: "Enervazione" },
  "enhance greed": { nameIt: "Aumentare l'Avidità" },
  "enrage architecture": { nameIt: "Infuriare l'Architettura" },
  "entomb": { nameIt: "Seppellire" },
  "entropic damage field": { nameIt: "Campo di Danno Entropico" },
  "erupting earth": { nameIt: "Terra Erompente" },
  "eruption": { nameIt: "Eruzione" },
  "essence instability": { nameIt: "Instabilità dell'Essenza" },
  "eternal echo": { nameIt: "Eco Eterno" },
  "ethereal stairs": { nameIt: "Scale Eteree" },
  "etherealness": { nameIt: "forma eterea" },
  "evard's black tentacles": { nameIt: "tentacoli neri di Evard" },
  "evercold": { nameIt: "Freddo Perenne" },
  "exchanged knowledge": { nameIt: "Conoscenza Scambiata" },
  "expeditious retreat": { nameIt: "ritirata rapida" },
  "exsanguinate": { nameIt: "Dissanguare" },
  "exsanguinating cloud": { nameIt: "Nube Dissanguante" },
  "extract foyson": { nameIt: "Estrarre Vigore" },
  "extract knowledge": { nameIt: "Estrarre Conoscenza" },
  "eye bite": { nameIt: "Morso del Globo Oculare" },
  "eyebite": { nameIt: "sguardo penetrante" },
  "faithful hound": { nameIt: "Levriero Fedele" },
  "far step": { nameIt: "Passo Altrove" },
  "fast friends": { nameIt: "Amici per la Pelle" },
  "fault line": { nameIt: "Linea di Faglia" },
  "fear": { nameIt: "paura" },
  "feather field": { nameIt: "Campo di Piume" },
  "feather travel": { nameIt: "Viaggio di Piuma" },
  "feeblemind": { nameIt: "regressione mentale" },
  "feed the worms": { nameIt: "Nutrire i Vermi" },
  "feign death": { nameIt: "morte apparente" },
  "feint": { nameIt: "Finta" },
  "fey crown": { nameIt: "Corona Fatata" },
  "fey food": { nameIt: "Cibo Fatato" },
  "fey-touched blade": { nameIt: "Lama Toccata dal Selvalfo" },
  "find greater steed": { nameIt: "Trovare Destriero Superiore" },
  "find kin": { nameIt: "Trovare Consanguinei" },
  "find steed": { nameIt: "trova cavalcatura" },
  "find the flaw": { nameIt: "Individuare il Difetto" },
  "find the path": { nameIt: "scopri il percorso" },
  "find traps": { nameIt: "scopri trappole" },
  "fire bolt": { nameIt: "dardo di fuoco" },
  "fire darts": { nameIt: "Dardi di Fuoco" },
  "fire under the tongue": { nameIt: "Fuoco sotto la Lingua" },
  "firewalk": { nameIt: "Camminare sul Fuoco" },
  "fist of iron": { nameIt: "Pugno di Ferro" },
  "fizban’s platinum shield": { nameIt: "Scudo di Platino di Fizban" },
  "flame arrows": { nameIt: "Frecce Infuocate" },
  "flame stride": { nameIt: "Passo Fiammeggiante" },
  "flame wave": { nameIt: "Onda di Fiamme" },
  "flesh to paper": { nameIt: "Da Carne a Carta" },
  "flex": { nameIt: "Contrazione" },
  "flickering fate": { nameIt: "Destino Vacillante" },
  "floating disk": { nameIt: "Disco Fluttuante" },
  "fluctuating alignment": { nameIt: "Allineamento Fluuttuante" },
  "flurry": { nameIt: "Raffica" },
  "forbiddance": { nameIt: "proibizione" },
  "force of will": { nameIt: "Forza di Volontà" },
  "force punch": { nameIt: "Pugno di Forza" },
  "forced reposition": { nameIt: "Riposizionamento Forzato" },
  "foresight": { nameIt: "previsione" },
  "forest army": { nameIt: "Esercito della Foresta" },
  "forest native": { nameIt: "Nativo della Foresta" },
  "forest sanctuary": { nameIt: "Santuario della Foresta" },
  "foretell distraction": { nameIt: "Prevedere Distrazione" },
  "form of the gods": { nameIt: "Forma degli Dei" },
  "fortune’s favor": { nameIt: "Favore della Fortuna" },
  "freeze blood": { nameIt: "Congelare il Sangue" },
  "freeze potion": { nameIt: "Congelare Pozione" },
  "freezing fog": { nameIt: "Nebbia Congelante" },
  "frenzied bolt": { nameIt: "Dardo Frenetico" },
  "friends": { nameIt: "amicizia" },
  "frost fingers": { nameIt: "Dita di Ghiaccio" },
  "frostbite": { nameIt: "Sottozero" },
  "frostbitten fingers": { nameIt: "Dita Assiderate" },
  "frozen razors": { nameIt: "Rasoi di Ghiaccio" },
  "furious hooves": { nameIt: "Zoccoli Furiosi" },
  "furious interdict": { nameIt: "Interdetto Furioso" },
  "furious wail": { nameIt: "Lamento Furioso" },
  "fuse armor": { nameIt: "Fondere Armatura" },
  "fusillade of ice": { nameIt: "Scarica di Ghiaccio" },
  "gale": { nameIt: "Burrasca" },
  "gate seal": { nameIt: "Sigillo del Portale" },
  "gear barrage": { nameIt: "Sbarramento di Ingranaggi" },
  "gear shield": { nameIt: "Scudo di Ingranaggi" },
  "geas": { nameIt: "costrizione" },
  "ghoul king’s cloak": { nameIt: "Mantello del Re dei Ghoul" },
  "giant insect": { nameIt: "insetto gigante" },
  "gift of azathoth": { nameIt: "Dono di Azathoth" },
  "gift of gab": { nameIt: "Dono della Parlantina" },
  "gird the spirit": { nameIt: "Cingere lo Spirito" },
  "glacial cascade": { nameIt: "Cascata Glaciale" },
  "glacial fog": { nameIt: "Nebbia Glaciale" },
  "glare": { nameIt: "Bagliore" },
  "glibness": { nameIt: "loquacità" },
  "gliding step": { nameIt: "Passo Scivolante" },
  "glimpse of the void": { nameIt: "Visione del Vuoto" },
  "gloomwrought barrier": { nameIt: "Barriera di Gloomwrought" },
  "gluey globule": { nameIt: "Globulo Vischioso" },
  "glyph of shifting": { nameIt: "Glifo di Spostamento" },
  "goat's hoof charm": { nameIt: "Incanto dello Zoccolo di Capra" },
  "going in circles": { nameIt: "Girare in Tondo" },
  "goodberry": { nameIt: "bacche benefiche" },
  "gordolay’s pleasant aroma": { nameIt: "Piacevole Aroma di Gordolay" },
  "grapevine": { nameIt: "Vite" },
  "grasp of the tupilak": { nameIt: "Presa del Tupilak" },
  "gravity fissure": { nameIt: "Fessura Gravitazionale" },
  "gravity sinkhole": { nameIt: "Voragine Gravitazionale" },
  "greater ley protection": { nameIt: "Protezione delle Linee Ley Superiore" },
  "greater ley pulse": { nameIt: "Impulso delle Linee Ley Superiore" },
  "greater maze": { nameIt: "Labirinto Superiore" },
  "greater seal of sanctuary": { nameIt: "Sigillo Superiore del Santuario" },
  "green decay": { nameIt: "Marciume Verde" },
  "gremlins": { nameIt: "Gremlin" },
  "grinding gears": { nameIt: "Ingranaggi Trituranti" },
  "grudge match": { nameIt: "Duello di Rancore" },
  "guardian of nature": { nameIt: "Guardiano della Natura" },
  "guards and wards": { nameIt: "vigilanza e interdizione" },
  "guest of honor": { nameIt: "Ospite d'Onore" },
  "guiding star": { nameIt: "Stella Guida" },
  "gust": { nameIt: "Folata" },
  "hail of thorns": { nameIt: "raffica di spine" },
  "hallow": { nameIt: "santificare" },
  "hamstring": { nameIt: "Recidere Tendini" },
  "hard heart": { nameIt: "Cuore di Pietra" },
  "harm": { nameIt: "ferire" },
  "harmonic resonance": { nameIt: "Risonanza Armonica" },
  "harry": { nameIt: "Tormentare" },
  "harrying hounds": { nameIt: "Segugi Tormentatori" },
  "harsh light of summer’s glare": { nameIt: "Luce Spietata dell'Abbaglio Estivo" },
  "healing spirit": { nameIt: "Spirito Guaritore" },
  "heart of dis": { nameIt: "Cuore di Dis" },
  "heart to heart": { nameIt: "Cuore a Cuore" },
  "heart-seeking arrow": { nameIt: "Freccia Cercacuore" },
  "heartache": { nameIt: "Crepacuore" },
  "hearth charm": { nameIt: "Incanto del Focolare" },
  "heartstop": { nameIt: "Fermacuore" },
  "heartstrike": { nameIt: "Colpo al Cuore" },
  "heat metal": { nameIt: "riscaldare il metallo" },
  "heavenly crown": { nameIt: "Corona Celeste" },
  "hedgehog dozen": { nameIt: "Dozzina di Ricci" },
  "hedren’s birds of clay": { nameIt: "Uccelli d'Argilla di Hedren" },
  "hell’s lash": { nameIt: "Frusta Infernale" },
  "hellforging": { nameIt: "Forgiatura Infernale" },
  "hellish rebuke": { nameIt: "intimorire infernale" },
  "hematomancy": { nameIt: "Ematomanzia" },
  "hero's steel": { nameIt: "Acciaio dell'Eroe" },
  "hide in one’s shadow": { nameIt: "Nascondersi nella Propria Ombra" },
  "high ground": { nameIt: "Terreno Rialzato" },
  "hirvsth's call": { nameIt: "Richiamo di Hirvsth" },
  "hoarfrost": { nameIt: "Brina" },
  "hobble": { nameIt: "Azzoppare" },
  "hobble mount": { nameIt: "Azzoppare Cavalcatura" },
  "hod's gift": { nameIt: "Dono di Hod" },
  "holy aura": { nameIt: "aura sacra" },
  "holy ground": { nameIt: "Terreno Sacro" },
  "holy weapon": { nameIt: "Arma Sacra" },
  "hone blade": { nameIt: "Affilare Lama" },
  "hunger of leng": { nameIt: "Fame di Leng" },
  "hunter's endurance": { nameIt: "Resistenza del Cacciatore" },
  "hunting stand": { nameIt: "Postazione di Caccia" },
  "hydraulic beam": { nameIt: "Raggio Idraulico" },
  "hypnagogia": { nameIt: "Ipnagogia" },
  "hypnic jerk": { nameIt: "Sussulto Ipnico" },
  "ice fortress": { nameIt: "Fortezza di Ghiaccio" },
  "ice hammer": { nameIt: "Martello di Ghiaccio" },
  "ice knife": { nameIt: "Coltello di Ghiaccio" },
  "ice soldiers": { nameIt: "Soldati di Ghiaccio" },
  "icicle daggers": { nameIt: "Pugnali di Ghiaccio" },
  "icingdeath’s frost": { nameIt: "Gelo di Gelomorte" },
  "icy grasp of the void": { nameIt: "Morsa Gelida del Vuoto" },
  "icy manipulation": { nameIt: "Manipolazione Gelida" },
  "ill-fated word": { nameIt: "Parola Infausta" },
  "illuminate spoor": { nameIt: "Illuminare Tracce" },
  "illusory dragon": { nameIt: "Drago Illusorio" },
  "imbue spell": { nameIt: "Infondere Incantesimo" },
  "immobilizing interdict": { nameIt: "Interdizione Immobilizzante" },
  "immolating gibbet": { nameIt: "Forca Immolante" },
  "immolation": { nameIt: "Immolazione" },
  "immovable object": { nameIt: "Oggetto Inamovibile" },
  "impending ally": { nameIt: "Alleato Imminente" },
  "imprisonment": { nameIt: "imprigionare" },
  "incantation of lies made truth": { nameIt: "Incanto delle Bugie Rese Verità" },
  "incite greed": { nameIt: "Incitare l'Avidità" },
  "inconspicuous facade": { nameIt: "Facciata Inosservata" },
  "inescapable malady": { nameIt: "Malattia Ineluttabile" },
  "inexorable summons": { nameIt: "Richiamo Inesorabile" },
  "infernal calling": { nameIt: "Richiamo Infernale" },
  "infernal weapon": { nameIt: "Arma Infernale" },
  "infestation": { nameIt: "Infestazione" },
  "innocuous aspect": { nameIt: "Aspetto Innocuo" },
  "insightful maneuver": { nameIt: "Manovra Intuitiva" },
  "inspiring speech": { nameIt: "Discorso Ispiratore" },
  "instant armored vehicle": { nameIt: "Veicolo Corazzato Istantaneo" },
  "instant fortification": { nameIt: "Fortificazione Istantanea" },
  "instant siege weapon": { nameIt: "Arma d'Assedio Istantanea" },
  "instant snare": { nameIt: "Cappio Istantaneo" },
  "instant summons": { nameIt: "Evocazione Istantanea" },
  "interdict iteritas": { nameIt: "Interdizione di Iteritas" },
  "invested champion": { nameIt: "Campione Investito" },
  "investiture of flame": { nameIt: "Investitura della Fiamma" },
  "investiture of ice": { nameIt: "Investitura del Ghiaccio" },
  "investiture of stone": { nameIt: "Investitura della Pietra" },
  "investiture of wind": { nameIt: "Investitura del Vento" },
  "invigorated strikes": { nameIt: "Colpi Rinvigoriti" },
  "invulnerability": { nameIt: "Invulnerabilità" },
  "ire of the mountain": { nameIt: "Ira della Montagna" },
  "iron gut": { nameIt: "Stomaco di Ferro" },
  "iron hand": { nameIt: "Mano di Ferro" },
  "jagged forcelance": { nameIt: "Lancia di Forza Dentellata" },
  "jarring growl": { nameIt: "Ringhio Discordante" },
  "jeweled fissure": { nameIt: "Fessura Gioiellata" },
  "jim’s glowing coin": { nameIt: "Moneta Luccicante di Jim" },
  "jim’s magic missile": { nameIt: "Dardo Incantato di Jim" },
  "jotun's jest": { nameIt: "Scherzo di Jotun" },
  "jump": { nameIt: "saltare" },
  "kareef’s entreaty": { nameIt: "Supplica di Kareef" },
  "keening wail": { nameIt: "Lamento Straziante" },
  "killing fields": { nameIt: "Campi di Sterminio" },
  "kinetic jaunt": { nameIt: "Escursione Cinetica" },
  "kiss of the succubus": { nameIt: "Bacio del Succubo" },
  "knock": { nameIt: "scassinare" },
  "kobold’s fury": { nameIt: "Furia del Coboldo" },
  "labyrinth mastery": { nameIt: "Maestria del Labirinto" },
  "labyrinthine howl": { nameIt: "Urlo Labirintico" },
  "lacerate": { nameIt: "Lacerare" },
  "lair sense": { nameIt: "Percepire la Tana" },
  "lance": { nameIt: "lancia da cavaliere" },
  "land bond": { nameIt: "Legame con la Terra" },
  "last rays of the dying sun": { nameIt: "Ultimi Raggi del Sole Morente" },
  "lava stone": { nameIt: "Pietra Lavica" },
  "lay to rest": { nameIt: "Concedere il Riposo" },
  "legend killer": { nameIt: "Uccisore di Leggende" },
  "legend lore": { nameIt: "conoscenza delle leggende" },
  "legion": { nameIt: "Legione" },
  "legion of rabid squirrels": { nameIt: "Legione di Scoiattoli Rabbiosi" },
  "lemure transformation": { nameIt: "Trasformazione in Lemure" },
  "leomund's secret chest": { nameIt: "scrigno segreto di Leomund" },
  "less fool, i": { nameIt: "Meno Sciocco Io" },
  "lesser ley protection": { nameIt: "Protezione di Ley Minore" },
  "lesser ley pulse": { nameIt: "Impulso di Ley Minore" },
  "lesser maze": { nameIt: "Labirinto Minore" },
  "levitate": { nameIt: "levitazione" },
  "ley disruption": { nameIt: "Interruzione di Ley" },
  "ley disturbance": { nameIt: "Perturbazione di Ley" },
  "ley energy bolt": { nameIt: "Dardo di Energia di Ley" },
  "ley leech": { nameIt: "Sanguisuga di Ley" },
  "ley sense": { nameIt: "Senso di Ley" },
  "ley storm": { nameIt: "Tempesta di Ley" },
  "ley surge": { nameIt: "Ondata di Ley" },
  "ley whip": { nameIt: "Frusta di Ley" },
  "life burst": { nameIt: "Esplosione di Vita" },
  "life drain": { nameIt: "Drenaggio Vitale" },
  "life from death": { nameIt: "Vita dalla Morte" },
  "life hack": { nameIt: "Trucco Vitale" },
  "life sense": { nameIt: "Percezione della Vita" },
  "life transference": { nameIt: "Trasferimento di Vita" },
  "life transference arrow": { nameIt: "Freccia del Trasferimento di Vita" },
  "lightless torch": { nameIt: "Torcia Senza Luce" },
  "lightning arrow": { nameIt: "freccia folgorante" },
  "litany of sure hands": { nameIt: "Litania delle Mani Sicure" },
  "living shadows": { nameIt: "Ombre Viventi" },
  "locate animals or plants": { nameIt: "Localizza Animali o Piante" },
  "locate red portal": { nameIt: "Localizza Portale Rosso" },
  "lock armor": { nameIt: "Blocca Armatura" },
  "loki's gift": { nameIt: "Dono di Loki" },
  "long game": { nameIt: "Lungo Gioco" },
  "longstrider": { nameIt: "passo veloce" },
  "looping trail": { nameIt: "Sentiero ad Anello" },
  "lovesick": { nameIt: "Mal d'Amore" },
  "machine sacrifice": { nameIt: "Sacrificio della Macchina" },
  "machine speech": { nameIt: "Linguaggio delle Macchine" },
  "machine's load": { nameIt: "Carico della Macchina" },
  "maddening darkness": { nameIt: "Oscurità Demenziale" },
  "maddening whispers": { nameIt: "Sussurri Demenziali" },
  "maelstrom": { nameIt: "Maelstrom" },
  "mage armor": { nameIt: "armatura magica" },
  "magic jar": { nameIt: "giara magica" },
  "magic mouth": { nameIt: "bocca magica" },
  "magic stone": { nameIt: "Pietra Magica" },
  "magma spray": { nameIt: "Spruzzo di Magma" },
  "magnetize": { nameIt: "Magnetizzare" },
  "magnificent mansion": { nameIt: "Magnifica Magione" },
  "magnify gravity": { nameIt: "Amplificare Gravità" },
  "maim": { nameIt: "Mutilare" },
  "malevolent waves": { nameIt: "Onde Malevole" },
  "mammon’s due": { nameIt: "Tributo di Mammona" },
  "mantle of the brave": { nameIt: "Mantello del Valoroso" },
  "march of the dead": { nameIt: "Marcia dei Morti" },
  "mark prey": { nameIt: "Marchiare la Preda" },
  "martyr's rally": { nameIt: "Adunata del Martire" },
  "mass blade ward": { nameIt: "Interdizione dalle Lame di Massa" },
  "mass faerie fire": { nameIt: "Fuoco Fatuo di Massa" },
  "mass heal": { nameIt: "guarigione di massa" },
  "mass hobble mount": { nameIt: "Intralciare Cavalcature di Massa" },
  "mass polymorph": { nameIt: "Metamorfosi di Massa" },
  "mass repair metal": { nameIt: "Riparare Metallo di Massa" },
  "mass suggestion": { nameIt: "suggestione di massa" },
  "mass surge dampener": { nameIt: "Smorzare Sovraccarico di Massa" },
  "maw of needles": { nameIt: "Fauci d'Aghi" },
  "maximilian’s earthen grasp": { nameIt: "Presa Terrogena di Maximilian" },
  "maze": { nameIt: "labirinto" },
  "mechanical union": { nameIt: "Unione Meccanica" },
  "melf's acid arrow": { nameIt: "freccia acida di Melf" },
  "melf’s minute meteors": { nameIt: "Minuscole Meteore di Melf" },
  "memento mori": { nameIt: "Memento Mori" },
  "mental barrier": { nameIt: "Barriera Mentale" },
  "mental grip": { nameIt: "Presa Mentale" },
  "mental prison": { nameIt: "Prigione Mentale" },
  "mephitic croak": { nameIt: "Gracidio Mefitico" },
  "meteor swarm": { nameIt: "sciame di meteore" },
  "mighty fortress": { nameIt: "Fortezza Possente" },
  "mind blank": { nameIt: "vuoto mentale" },
  "mind exchange": { nameIt: "Scambio Mentale" },
  "mind maze": { nameIt: "Labirinto Mentale" },
  "mind spike": { nameIt: "Spina Mentale" },
  "mind thrust": { nameIt: "Stoccata Mentale" },
  "mindshield": { nameIt: "Scudo Mentale" },
  "mirage arcane": { nameIt: "miraggio arcano" },
  "mire": { nameIt: "Pantano" },
  "mirror realm": { nameIt: "Regno degli Specchi" },
  "misdirection": { nameIt: "Falsa Pista" },
  "misstep": { nameIt: "Passo Falso" },
  "mist of wonders": { nameIt: "Nebbia dei Prodigi" },
  "mold earth": { nameIt: "Plasmare Terra" },
  "molech's blessing": { nameIt: "Benedizione di Molech" },
  "monstrous empathy": { nameIt: "Empatia Mostruosa" },
  "moon trap": { nameIt: "Trappola Lunare" },
  "moon's respite": { nameIt: "Tregua della Luna" },
  "mordenkainen's faithful hound": { nameIt: "segugio fedele di Mordenkainen" },
  "mordenkainen's magnificent mansion": { nameIt: "reggia meravigliosa di Mordenkainen" },
  "mordenkainen’s sword": { nameIt: "Spada di Mordenkainen" },
  "morphic flux": { nameIt: "Flusso Morfico" },
  "mosquito bane": { nameIt: "Flagello delle Zanzare" },
  "motivational speech": { nameIt: "Discorso Motivazionale" },
  "move the cosmic wheel": { nameIt: "Muovere la Ruota Cosmica" },
  "mud": { nameIt: "Fango" },
  "mud pack": { nameIt: "Impacco di Fango" },
  "muted foe": { nameIt: "Nemico Silenziato" },
  "nathair’s mischief": { nameIt: "Dispetto di Nathair" },
  "negative energy flood": { nameIt: "Marea di Energia Negativa" },
  "negative image": { nameIt: "Immagine Negativa" },
  "nether weapon": { nameIt: "Arma degli Inferi" },
  "never surrender": { nameIt: "Mai Arrendersi" },
  "night terrors": { nameIt: "Terrori Notturni" },
  "nightfall": { nameIt: "Calar della Notte" },
  "nip at the heels": { nameIt: "Morso alle Calcagna" },
  "not dead yet": { nameIt: "Non Ancora Morto" },
  "not this day!": { nameIt: "Non Oggi!" },
  "oathbound implement": { nameIt: "Strumento Vincolato dal Giuramento" },
  "obfuscate object": { nameIt: "Offuscare Oggetto" },
  "open red portal": { nameIt: "Aprire Portale Rosso" },
  "orb of light": { nameIt: "Sfera di Luce" },
  "order of revenge": { nameIt: "Ordine di Vendetta" },
  "otiluke's freezing sphere": { nameIt: "sfera congelante di Otiluke" },
  "otiluke's resilient sphere": { nameIt: "sfera elastica di Otiluke" },
  "outflanking boon": { nameIt: "Dono del Fiancheggiamento" },
  "outmaneuver": { nameIt: "Superare in Manovra" },
  "overclock": { nameIt: "Sovraccaricare" },
  "oversized paws": { nameIt: "Zampe Smisurate" },
  "paragon of chaos": { nameIt: "Campione del Caos" },
  "pendulum": { nameIt: "Pendolo" },
  "perun's doom": { nameIt: "Rovina di Perun" },
  "pestilence": { nameIt: "Pestilenza" },
  "phantasmal talons": { nameIt: "Artigli Illusori" },
  "phantom dragon": { nameIt: "Drago Fantomatico" },
  "phantom steed": { nameIt: "destriero fantomatico" },
  "pierce the veil": { nameIt: "Squarciare il Velo" },
  "pincer": { nameIt: "Chela" },
  "piper's lure": { nameIt: "Richiamo del Pifferaio" },
  "pitfall": { nameIt: "Trabocchetto" },
  "planar ally": { nameIt: "alleato planare" },
  "poison gas": { nameIt: "Gas Velenoso" },
  "poison skin": { nameIt: "Pelle Velenosa" },
  "poison spray": { nameIt: "Spruzzo Velenoso" },
  "poisoned volley": { nameIt: "Salva Avvelenata" },
  "portal jaunt": { nameIt: "Balzo del Portale" },
  "portal trap": { nameIt: "Trappola del Portale" },
  "potency of the pack": { nameIt: "Potenza del Branco" },
  "power word fling": { nameIt: "Parola del Potere: Scagliare" },
  "power word kill": { nameIt: "parola del potere uccidere" },
  "power word kneel": { nameIt: "Parola del Potere: Inginocchiarsi" },
  "power word pain": { nameIt: "Parola del Potere: Dolore" },
  "power word rend": { nameIt: "Parola del Potere: Lacerare" },
  "power word restore": { nameIt: "Parola del Potere: Ripristinare" },
  "power word stun": { nameIt: "parola del potere stordire" },
  "pratfall": { nameIt: "Scivolone" },
  "prestidigitation": { nameIt: "prestidigitazione" },
  "primal infusion": { nameIt: "Infusione Primordiale" },
  "primal savagery": { nameIt: "Selvaggità Primordiale" },
  "primordial ward": { nameIt: "Interdizione Primordiale" },
  "prismatic ray": { nameIt: "Raggio Prismatico" },
  "private sanctum": { nameIt: "Santuario Privato" },
  "produce flame": { nameIt: "produrre fiamma" },
  "programmed illusion": { nameIt: "illusione programmata" },
  "project image": { nameIt: "immagine proiettata" },
  "protection from poison": { nameIt: "protezione dai veleni" },
  "protection from the void": { nameIt: "Protezione dal Vuoto" },
  "protective ice": { nameIt: "Ghiaccio Protettivo" },
  "psionic blast": { nameIt: "Esplosione Psionica" },
  "psychic crush": { nameIt: "Frantumazione Psichica" },
  "psychic scream": { nameIt: "Urlo Psichico" },
  "puff of smoke": { nameIt: "Sbuffo di Fumo" },
  "pulse wave": { nameIt: "Onda Pulsante" },
  "pummelstone": { nameIt: "Pietra Percotente" },
  "purify food and drink": { nameIt: "purificare cibo e bevande" },
  "putrescent faerie circle": { nameIt: "Cerchio Fatato Putrescente" },
  "pyroclasm": { nameIt: "Piroclasma" },
  "pyrotechnics": { nameIt: "Pirotecnica" },
  "quick time": { nameIt: "Tempo Rapido" },
  "quicken": { nameIt: "Velocizzare" },
  "quicksilver mantle": { nameIt: "Mantello d'Argento Vivo" },
  "quintessence": { nameIt: "Quintessenza" },
  "rage of the meek": { nameIt: "Rabbia dei Deboli" },
  "raid the lair": { nameIt: "Assalto al Covo" },
  "rain of blades": { nameIt: "Pioggia di Lame" },
  "raise hell": { nameIt: "Scatenare l'Inferno" },
  "raulothim’s psychic lance": { nameIt: "Lancia Psichica di Raulothim" },
  "ravenous void": { nameIt: "Vuoto Vorace" },
  "ray of alchemical negation": { nameIt: "Raggio di Negazione Alchemica" },
  "ray of frost": { nameIt: "raggio di gelo" },
  "ray of life suppression": { nameIt: "Raggio di Soppressione della Vita" },
  "read memory": { nameIt: "Leggere Memoria" },
  "reality break": { nameIt: "Frattura della Realtà" },
  "reaper's knell": { nameIt: "Rintocco del Mietitore" },
  "reassemble": { nameIt: "Riassemblare" },
  "reaver spirit": { nameIt: "Spirito Predone" },
  "rebounding bolt": { nameIt: "Dardo Rimbalzante" },
  "reciprocating portal": { nameIt: "Portale Reciproco" },
  "regenerate": { nameIt: "rigenerazione" },
  "reincarnate": { nameIt: "reincarnazione" },
  "rejuvenating interdict": { nameIt: "Interdetto Rigenerante" },
  "remove curse": { nameIt: "rimuovi maledizione" },
  "remove insulation": { nameIt: "Rimuovere Isolamento" },
  "repair metal": { nameIt: "Riparare Metallo" },
  "reposition": { nameIt: "Riposizionare" },
  "repulsing wall": { nameIt: "Muro Respingente" },
  "reset": { nameIt: "Ripristinare" },
  "reset red portal": { nameIt: "Ripristinare il Portale Rosso" },
  "resistance": { nameIt: "resistenza" },
  "resurrection": { nameIt: "resurrezione" },
  "retribution": { nameIt: "Castigo" },
  "revenge's eye": { nameIt: "Occhio della Vendetta" },
  "reverberate": { nameIt: "Riverberare" },
  "reverse gravity": { nameIt: "inversione della gravità" },
  "revive beast": { nameIt: "Rianimare Bestia" },
  "right the stars": { nameIt: "Allineare le Stelle" },
  "rime’s binding ice": { nameIt: "Ghiaccio Vincolante di Rime" },
  "ring strike": { nameIt: "Colpo dell'Anello" },
  "ring ward": { nameIt: "Protezione dell'Anello" },
};
